# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 882aea3012ed7ec8401406ca56273082b20a81d8f3ef287781b3541eb9c3e766d1f33a465a934602d03122526750689956f525e9d9c3cbd86d92d2f1a358d7f6

test:
  secret_key_base: db4b8968549452525424d2b65d5c2f6b3e5843f2576f4cb4e81697eaacb8251e12ac8f7d779fa06ca8855ffa8117ef8661d8feb8ff1aad503d6da5c43980cae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
