# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28383cca05ba98361bd022410ae9f40c792128ec2cca720cb5c2f074779a995ea1ead61c2df41556954925a16854d2bebab59785bb98a61fd5a97d4e04e11c06

test:
  secret_key_base: fa4ded0440ce7eccffa4030ca07af1f43aa8f934776a4622ddc6368886a358ed5d156844b0ba2d64db3c12cf079b92db5ec0b3cbaa5c58d1a25f38e5702dd42d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
