# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61452eb2020c257b2b1b1b1cf531de4a7354148dd3d80added6be8a548cf140813938fb7911883789c096f5d329d5c324c168d5f683fda7032a517ae1490657d

test:
  secret_key_base: e334a5bf9be99d046dcf6cf1084dcc818e7d02131368f793d54a0a28b21db9be59fa6d7e47e4e8483088c2de2ad04720e4c20486d657960a1a3ebb32e25f0375

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
